spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testgit?serverTimezone=UTC
    username: root
    password: root
    schema:
    # - classpath:person.sql
    #initialization-mode: always
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 10
    maxActive: 20

mybatis:
  configuration:
    map-underscore-to-camel-case: true

